### PR TITLE
import h2o and libwslay

### PR DESCRIPTION
**Pull request by Habbie**

### CODE REVIEW

**Comment by diizzyy** [comment]
h2o is doa, https://github.com/h2o/h2o/issues/3230

PKG_SOURCE:=release-$(PKG_VERSION).tar.gz is a no go for wslay
Have a look at https://github.com/openwrt/packages/blob/master/sound/fdk-aac/Makefile#L12

**Comment by neheb** [comment]
hmm? this is for abandoned packages.

**Comment by BKPepe** [comment]
Even though it was wrong from the beginning, it does not mean it will stay like this, doesn't it? :) We can fix it even for abandoned packages.

**Comment by Habbie** [comment]
> h2o is doa, [h2o/h2o#3230](https://github.com/h2o/h2o/issues/3230)

that is why nothing in openwrt depends on it any more :)

**Comment by Habbie** [comment]
> PKG_SOURCE:=release-$(PKG_VERSION).tar.gz is a no go for wslay

I imported the Makefile from packages, where it works.

**Comment by hauke** [comment]
I think there is no need to add something to packages-abandoned. I am not a maintainer of the feeds, if you want that it is fine with me. 
We tried to use use https://github.com/openwrt/targets for old targets, but I am not aware that anyone took anything from this feed. 
If someone wants the code back in the future the person can get it from the git history.

**Comment by Habbie** [comment]
thanks hauke, I'll close this.

**Pull request closed without merging**
